import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { Map, MapMarker } from 'react-kakao-maps-sdk';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <script
                    type="text/javascript"
                    src="//dapi.kakao.com/v2/maps/sdk.js?appkey=4d8c337f255e4d10bce42da9f269c2a1&libraries=services,clusterer"
                ></script>
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <Map
                    center={{ lat: 33.5563, lng: 126.79581 }}
                    style={{ width: '100%', height: '360px' }}
                >
                    <MapMarker position={{ lat: 33.55635, lng: 126.795841 }}>
                        <div style={{ color: '#000' }}>Hello World!</div>
                    </MapMarker>
                </Map>
            </main>
        </>
    );
}
