name: Publish Docker Hub

on:
    push:
        branches: [main]
jobs:
  docker:
      name: Deploy Docker Image
      runs-on: ubuntu-latest
      env:
          REPO: ${{ secrets.DOCKER_REPO }}
      steps:
          - uses: actions/checkout@v3
          - name: Setting .env
            run: |
              echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> .env
              echo "NEXT_PUBLIC_KAKAO_MAP_API_KEY=${{ secrets.NEXT_PUBLIC_KAKAO_MAP_API_KEY }}" >> .env
              echo "NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}" >> .env
              echo "NEXT_PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_VAPID_PUBLIC_KEY }}" >> .env
              echo "NEXT_PUBLIC_VAPID_PRIVATE_KEY=${{ secrets.NEXT_PUBLIC_VAPID_PRIVATE_KEY }}" >> .env
              echo "NEXT_PUBLIC_VAPID_SUBJECT=${{ secrets.NEXT_PUBLIC_VAPID_SUBJECT }}" >> .env
          - name: build docker
            run: docker build . -t $REPO:${{ github.sha }}
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Publish Docker Image
            run: |
                docker push $REPO:${{ github.sha }}